const DataAnimeWorldExample = [
 {
  mal_id: 51009,
  url: "https://myanimelist.net/anime/51009/Jujutsu_Kaisen_2nd_Season",
  images: {
   jpg: {
    image_url: "https://cdn.myanimelist.net/images/anime/1600/134703.jpg",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1600/134703t.jpg",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1600/134703l.jpg",
   },
   webp: {
    image_url: "https://cdn.myanimelist.net/images/anime/1600/134703.webp",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1600/134703t.webp",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1600/134703l.webp",
   },
  },
  trailer: {
   youtube_id: "O6qVieflwqs",
   url: "https://www.youtube.com/watch?v=O6qVieflwqs",
   embed_url: "https://www.youtube.com/embed/O6qVieflwqs?enablejsapi=1&wmode=opaque&autoplay=1",
   images: {
    image_url: "https://img.youtube.com/vi/O6qVieflwqs/default.jpg",
    small_image_url: "https://img.youtube.com/vi/O6qVieflwqs/sddefault.jpg",
    medium_image_url: "https://img.youtube.com/vi/O6qVieflwqs/mqdefault.jpg",
    large_image_url: "https://img.youtube.com/vi/O6qVieflwqs/hqdefault.jpg",
    maximum_image_url: "https://img.youtube.com/vi/O6qVieflwqs/maxresdefault.jpg",
   },
  },
  approved: true,
  titles: [
   {
    type: "Default",
    title: "Jujutsu Kaisen 2nd Season",
   },
   {
    type: "Synonym",
    title: "Sorcery Fight",
   },
   {
    type: "Synonym",
    title: "JJK",
   },
   {
    type: "Japanese",
    title: "呪術廻戦",
   },
  ],
  title: "Jujutsu Kaisen 2nd Season",
  title_english: null,
  title_japanese: "呪術廻戦",
  title_synonyms: ["Sorcery Fight", "JJK"],
  type: "TV",
  source: "Manga",
  episodes: 23,
  status: "Currently Airing",
  airing: true,
  aired: {
   from: "2023-07-06T00:00:00+00:00",
   to: null,
   prop: {
    from: {
     day: 6,
     month: 7,
     year: 2023,
    },
    to: {
     day: null,
     month: null,
     year: null,
    },
   },
   string: "Jul 6, 2023 to ?",
  },
  duration: "23 min per ep",
  rating: "R - 17+ (violence & profanity)",
  score: 8.81,
  scored_by: 76456,
  rank: 32,
  popularity: 387,
  members: 536783,
  favorites: 7476,
  synopsis: "Second season of Jujutsu Kaisen.",
  background: null,
  season: "summer",
  year: 2023,
  broadcast: {
   day: "Thursdays",
   time: "23:56",
   timezone: "Asia/Tokyo",
   string: "Thursdays at 23:56 (JST)",
  },
  producers: [
   {
    mal_id: 143,
    type: "anime",
    name: "Mainichi Broadcasting System",
    url: "https://myanimelist.net/anime/producer/143/Mainichi_Broadcasting_System",
   },
   {
    mal_id: 1143,
    type: "anime",
    name: "TOHO animation",
    url: "https://myanimelist.net/anime/producer/1143/TOHO_animation",
   },
   {
    mal_id: 1365,
    type: "anime",
    name: "Shueisha",
    url: "https://myanimelist.net/anime/producer/1365/Shueisha",
   },
   {
    mal_id: 1856,
    type: "anime",
    name: "dugout",
    url: "https://myanimelist.net/anime/producer/1856/dugout",
   },
   {
    mal_id: 2260,
    type: "anime",
    name: "Sumzap",
    url: "https://myanimelist.net/anime/producer/2260/Sumzap",
   },
  ],
  licensors: [],
  studios: [
   {
    mal_id: 569,
    type: "anime",
    name: "MAPPA",
    url: "https://myanimelist.net/anime/producer/569/MAPPA",
   },
  ],
  genres: [
   {
    mal_id: 1,
    type: "anime",
    name: "Action",
    url: "https://myanimelist.net/anime/genre/1/Action",
   },
   {
    mal_id: 10,
    type: "anime",
    name: "Fantasy",
    url: "https://myanimelist.net/anime/genre/10/Fantasy",
   },
  ],
  explicit_genres: [],
  themes: [
   {
    mal_id: 23,
    type: "anime",
    name: "School",
    url: "https://myanimelist.net/anime/genre/23/School",
   },
  ],
  demographics: [
   {
    mal_id: 27,
    type: "anime",
    name: "Shounen",
    url: "https://myanimelist.net/anime/genre/27/Shounen",
   },
  ],
 },
 {
  mal_id: 51179,
  url: "https://myanimelist.net/anime/51179/Mushoku_Tensei_II__Isekai_Ittara_Honki_Dasu",
  images: {
   jpg: {
    image_url: "https://cdn.myanimelist.net/images/anime/1732/137465.jpg",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1732/137465t.jpg",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1732/137465l.jpg",
   },
   webp: {
    image_url: "https://cdn.myanimelist.net/images/anime/1732/137465.webp",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1732/137465t.webp",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1732/137465l.webp",
   },
  },
  trailer: {
   youtube_id: "keti2rbgI6c",
   url: "https://www.youtube.com/watch?v=keti2rbgI6c",
   embed_url: "https://www.youtube.com/embed/keti2rbgI6c?enablejsapi=1&wmode=opaque&autoplay=1",
   images: {
    image_url: "https://img.youtube.com/vi/keti2rbgI6c/default.jpg",
    small_image_url: "https://img.youtube.com/vi/keti2rbgI6c/sddefault.jpg",
    medium_image_url: "https://img.youtube.com/vi/keti2rbgI6c/mqdefault.jpg",
    large_image_url: "https://img.youtube.com/vi/keti2rbgI6c/hqdefault.jpg",
    maximum_image_url: "https://img.youtube.com/vi/keti2rbgI6c/maxresdefault.jpg",
   },
  },
  approved: true,
  titles: [
   {
    type: "Default",
    title: "Mushoku Tensei II: Isekai Ittara Honki Dasu",
   },
   {
    type: "Synonym",
    title: "Jobless Reincarnation: I Will Seriously Try If I Go To Another World",
   },
   {
    type: "Synonym",
    title: "Mushoku Tensei: Isekai Ittara Honki Dasu 2nd Season",
   },
   {
    type: "Japanese",
    title: "無職転生 II ～異世界行ったら本気だす～",
   },
   {
    type: "English",
    title: "Mushoku Tensei: Jobless Reincarnation Season 2",
   },
  ],
  title: "Mushoku Tensei II: Isekai Ittara Honki Dasu",
  title_english: "Mushoku Tensei: Jobless Reincarnation Season 2",
  title_japanese: "無職転生 II ～異世界行ったら本気だす～",
  title_synonyms: [
   "Jobless Reincarnation: I Will Seriously Try If I Go To Another World",
   "Mushoku Tensei: Isekai Ittara Honki Dasu 2nd Season",
  ],
  type: "TV",
  source: "Light novel",
  episodes: 12,
  status: "Currently Airing",
  airing: true,
  aired: {
   from: "2023-07-10T00:00:00+00:00",
   to: null,
   prop: {
    from: {
     day: 10,
     month: 7,
     year: 2023,
    },
    to: {
     day: null,
     month: null,
     year: null,
    },
   },
   string: "Jul 10, 2023 to ?",
  },
  duration: "23 min per ep",
  rating: "R - 17+ (violence & profanity)",
  score: 8.57,
  scored_by: 49930,
  rank: 93,
  popularity: 630,
  members: 352958,
  favorites: 4312,
  synopsis: "Second season of Mushoku Tensei: Isekai Ittara Honki Dasu.",
  background: null,
  season: "summer",
  year: 2023,
  broadcast: {
   day: "Mondays",
   time: "00:00",
   timezone: "Asia/Tokyo",
   string: "Mondays at 00:00 (JST)",
  },
  producers: [
   {
    mal_id: 61,
    type: "anime",
    name: "Frontier Works",
    url: "https://myanimelist.net/anime/producer/61/Frontier_Works",
   },
   {
    mal_id: 1143,
    type: "anime",
    name: "TOHO animation",
    url: "https://myanimelist.net/anime/producer/1143/TOHO_animation",
   },
   {
    mal_id: 1333,
    type: "anime",
    name: "Hakuhodo DY Music & Pictures",
    url: "https://myanimelist.net/anime/producer/1333/Hakuhodo_DY_Music___Pictures",
   },
   {
    mal_id: 1416,
    type: "anime",
    name: "BS11",
    url: "https://myanimelist.net/anime/producer/1416/BS11",
   },
   {
    mal_id: 1444,
    type: "anime",
    name: "Egg Firm",
    url: "https://myanimelist.net/anime/producer/1444/Egg_Firm",
   },
   {
    mal_id: 1696,
    type: "anime",
    name: "Kadokawa",
    url: "https://myanimelist.net/anime/producer/1696/Kadokawa",
   },
   {
    mal_id: 2289,
    type: "anime",
    name: "GREE Entertainment",
    url: "https://myanimelist.net/anime/producer/2289/GREE_Entertainment",
   },
  ],
  licensors: [],
  studios: [
   {
    mal_id: 1993,
    type: "anime",
    name: "Studio Bind",
    url: "https://myanimelist.net/anime/producer/1993/Studio_Bind",
   },
  ],
  genres: [
   {
    mal_id: 8,
    type: "anime",
    name: "Drama",
    url: "https://myanimelist.net/anime/genre/8/Drama",
   },
   {
    mal_id: 10,
    type: "anime",
    name: "Fantasy",
    url: "https://myanimelist.net/anime/genre/10/Fantasy",
   },
   {
    mal_id: 9,
    type: "anime",
    name: "Ecchi",
    url: "https://myanimelist.net/anime/genre/9/Ecchi",
   },
  ],
  explicit_genres: [],
  themes: [
   {
    mal_id: 62,
    type: "anime",
    name: "Isekai",
    url: "https://myanimelist.net/anime/genre/62/Isekai",
   },
   {
    mal_id: 72,
    type: "anime",
    name: "Reincarnation",
    url: "https://myanimelist.net/anime/genre/72/Reincarnation",
   },
  ],
  demographics: [],
 },
 {
  mal_id: 54112,
  url: "https://myanimelist.net/anime/54112/Zom_100__Zombie_ni_Naru_made_ni_Shitai_100_no_Koto",
  images: {
   jpg: {
    image_url: "https://cdn.myanimelist.net/images/anime/1384/136408.jpg",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1384/136408t.jpg",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1384/136408l.jpg",
   },
   webp: {
    image_url: "https://cdn.myanimelist.net/images/anime/1384/136408.webp",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1384/136408t.webp",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1384/136408l.webp",
   },
  },
  trailer: {
   youtube_id: "GAMrUx-esS8",
   url: "https://www.youtube.com/watch?v=GAMrUx-esS8",
   embed_url: "https://www.youtube.com/embed/GAMrUx-esS8?enablejsapi=1&wmode=opaque&autoplay=1",
   images: {
    image_url: "https://img.youtube.com/vi/GAMrUx-esS8/default.jpg",
    small_image_url: "https://img.youtube.com/vi/GAMrUx-esS8/sddefault.jpg",
    medium_image_url: "https://img.youtube.com/vi/GAMrUx-esS8/mqdefault.jpg",
    large_image_url: "https://img.youtube.com/vi/GAMrUx-esS8/hqdefault.jpg",
    maximum_image_url: "https://img.youtube.com/vi/GAMrUx-esS8/maxresdefault.jpg",
   },
  },
  approved: true,
  titles: [
   {
    type: "Default",
    title: "Zom 100: Zombie ni Naru made ni Shitai 100 no Koto",
   },
   {
    type: "Synonym",
    title: "Bucket List of The Dead",
   },
   {
    type: "Synonym",
    title: "Zombie 100: 100 Things I Want to do Before I Become a Zombie",
   },
   {
    type: "Japanese",
    title: "ゾン100～ゾンビになるまでにしたい100のこと～",
   },
   {
    type: "English",
    title: "Zom 100: Bucket List of the Dead",
   },
  ],
  title: "Zom 100: Zombie ni Naru made ni Shitai 100 no Koto",
  title_english: "Zom 100: Bucket List of the Dead",
  title_japanese: "ゾン100～ゾンビになるまでにしたい100のこと～",
  title_synonyms: ["Bucket List of The Dead", "Zombie 100: 100 Things I Want to do Before I Become a Zombie"],
  type: "TV",
  source: "Manga",
  episodes: 12,
  status: "Currently Airing",
  airing: true,
  aired: {
   from: "2023-07-09T00:00:00+00:00",
   to: null,
   prop: {
    from: {
     day: 9,
     month: 7,
     year: 2023,
    },
    to: {
     day: null,
     month: null,
     year: null,
    },
   },
   string: "Jul 9, 2023 to ?",
  },
  duration: "24 min per ep",
  rating: "R - 17+ (violence & profanity)",
  score: 8.25,
  scored_by: 54693,
  rank: 298,
  popularity: 719,
  members: 313551,
  favorites: 2007,
  synopsis:
   "After graduating from a top university with an impressive extracurricular record in the rugby club, Akira Tendou has nailed every step of the way to securing his dream job. On top of that, a beautiful and kind co-worker always brightens his day in the office! Life seems to be going very well for Akira until he slowly realizes that sleepless nights and brutal work are his new reality.\n\nDue to three years of mind-numbing labor in an exploitative company, Akira is unable to recognize the tired, unaccomplished person he has become. On track to losing all passion in life like several of his overworked colleagues, Akira finds his saving grace in the most unexpected way possible—the breakout of a zombie apocalypse.\n\nWith the free time he finally has, Akira decides to complete a bucket list of a hundred things he wants to do before he eventually gets turned into a zombie. Although he is surrounded by the dead, Akira has never felt more alive!\n\n[Written by MAL Rewrite]",
  background:
   "The anime is part of a production deal between VIZ Media, Shogakukan, and Shogakukan-Shueisha Productions.",
  season: "summer",
  year: 2023,
  broadcast: {
   day: "Sundays",
   time: "17:00",
   timezone: "Asia/Tokyo",
   string: "Sundays at 17:00 (JST)",
  },
  producers: [
   {
    mal_id: 62,
    type: "anime",
    name: "Shogakukan-Shueisha Productions",
    url: "https://myanimelist.net/anime/producer/62/Shogakukan-Shueisha_Productions",
   },
   {
    mal_id: 1856,
    type: "anime",
    name: "dugout",
    url: "https://myanimelist.net/anime/producer/1856/dugout",
   },
  ],
  licensors: [
   {
    mal_id: 119,
    type: "anime",
    name: "VIZ Media",
    url: "https://myanimelist.net/anime/producer/119/VIZ_Media",
   },
  ],
  studios: [
   {
    mal_id: 2674,
    type: "anime",
    name: "BUG FILMS",
    url: "https://myanimelist.net/anime/producer/2674/BUG_FILMS",
   },
  ],
  genres: [
   {
    mal_id: 1,
    type: "anime",
    name: "Action",
    url: "https://myanimelist.net/anime/genre/1/Action",
   },
   {
    mal_id: 4,
    type: "anime",
    name: "Comedy",
    url: "https://myanimelist.net/anime/genre/4/Comedy",
   },
   {
    mal_id: 14,
    type: "anime",
    name: "Horror",
    url: "https://myanimelist.net/anime/genre/14/Horror",
   },
   {
    mal_id: 37,
    type: "anime",
    name: "Supernatural",
    url: "https://myanimelist.net/anime/genre/37/Supernatural",
   },
   {
    mal_id: 41,
    type: "anime",
    name: "Suspense",
    url: "https://myanimelist.net/anime/genre/41/Suspense",
   },
  ],
  explicit_genres: [],
  themes: [
   {
    mal_id: 50,
    type: "anime",
    name: "Adult Cast",
    url: "https://myanimelist.net/anime/genre/50/Adult_Cast",
   },
   {
    mal_id: 76,
    type: "anime",
    name: "Survival",
    url: "https://myanimelist.net/anime/genre/76/Survival",
   },
  ],
  demographics: [
   {
    mal_id: 42,
    type: "anime",
    name: "Seinen",
    url: "https://myanimelist.net/anime/genre/42/Seinen",
   },
  ],
 },
 {
  mal_id: 40357,
  url: "https://myanimelist.net/anime/40357/Tate_no_Yuusha_no_Nariagari_Season_3",
  images: {
   jpg: {
    image_url: "https://cdn.myanimelist.net/images/anime/1188/136926.jpg",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1188/136926t.jpg",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1188/136926l.jpg",
   },
   webp: {
    image_url: "https://cdn.myanimelist.net/images/anime/1188/136926.webp",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1188/136926t.webp",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1188/136926l.webp",
   },
  },
  trailer: {
   youtube_id: "VW_LxM4tt-o",
   url: "https://www.youtube.com/watch?v=VW_LxM4tt-o",
   embed_url: "https://www.youtube.com/embed/VW_LxM4tt-o?enablejsapi=1&wmode=opaque&autoplay=1",
   images: {
    image_url: "https://img.youtube.com/vi/VW_LxM4tt-o/default.jpg",
    small_image_url: "https://img.youtube.com/vi/VW_LxM4tt-o/sddefault.jpg",
    medium_image_url: "https://img.youtube.com/vi/VW_LxM4tt-o/mqdefault.jpg",
    large_image_url: "https://img.youtube.com/vi/VW_LxM4tt-o/hqdefault.jpg",
    maximum_image_url: "https://img.youtube.com/vi/VW_LxM4tt-o/maxresdefault.jpg",
   },
  },
  approved: true,
  titles: [
   {
    type: "Default",
    title: "Tate no Yuusha no Nariagari Season 3",
   },
   {
    type: "Synonym",
    title: "Tate no Yuusha no Nariagari 3rd Season",
   },
   {
    type: "Synonym",
    title: "The Rising of the Shield Hero 3rd Season",
   },
   {
    type: "Japanese",
    title: "盾の勇者の成り上がり",
   },
   {
    type: "English",
    title: "The Rising of the Shield Hero Season 3",
   },
  ],
  title: "Tate no Yuusha no Nariagari Season 3",
  title_english: "The Rising of the Shield Hero Season 3",
  title_japanese: "盾の勇者の成り上がり",
  title_synonyms: ["Tate no Yuusha no Nariagari 3rd Season", "The Rising of the Shield Hero 3rd Season"],
  type: "TV",
  source: "Light novel",
  episodes: null,
  status: "Currently Airing",
  airing: true,
  aired: {
   from: "2023-08-05T00:00:00+00:00",
   to: null,
   prop: {
    from: {
     day: 5,
     month: 8,
     year: 2023,
    },
    to: {
     day: null,
     month: null,
     year: null,
    },
   },
   string: "Aug 5, 2023 to ?",
  },
  duration: "Unknown",
  rating: "PG-13 - Teens 13 or older",
  score: 6.82,
  scored_by: 289,
  rank: 4880,
  popularity: 744,
  members: 305125,
  favorites: 5027,
  synopsis:
   "Third season of Tate no Yuusha no Nariagari.\n\nEpisodes 1 and 2 were previewed at a screening at AnimagiC in Mannheim, Germany on August 5, 2023. Regular broadcasting began in October 2023.",
  background: null,
  season: "summer",
  year: 2023,
  broadcast: {
   day: null,
   time: null,
   timezone: null,
   string: "Unknown",
  },
  producers: [
   {
    mal_id: 1696,
    type: "anime",
    name: "Kadokawa",
    url: "https://myanimelist.net/anime/producer/1696/Kadokawa",
   },
  ],
  licensors: [],
  studios: [
   {
    mal_id: 290,
    type: "anime",
    name: "Kinema Citrus",
    url: "https://myanimelist.net/anime/producer/290/Kinema_Citrus",
   },
  ],
  genres: [
   {
    mal_id: 1,
    type: "anime",
    name: "Action",
    url: "https://myanimelist.net/anime/genre/1/Action",
   },
   {
    mal_id: 2,
    type: "anime",
    name: "Adventure",
    url: "https://myanimelist.net/anime/genre/2/Adventure",
   },
   {
    mal_id: 8,
    type: "anime",
    name: "Drama",
    url: "https://myanimelist.net/anime/genre/8/Drama",
   },
   {
    mal_id: 10,
    type: "anime",
    name: "Fantasy",
    url: "https://myanimelist.net/anime/genre/10/Fantasy",
   },
  ],
  explicit_genres: [],
  themes: [
   {
    mal_id: 62,
    type: "anime",
    name: "Isekai",
    url: "https://myanimelist.net/anime/genre/62/Isekai",
   },
  ],
  demographics: [],
 },
 {
  mal_id: 54856,
  url: "https://myanimelist.net/anime/54856/Horimiya__Piece",
  images: {
   jpg: {
    image_url: "https://cdn.myanimelist.net/images/anime/1007/136277.jpg",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1007/136277t.jpg",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1007/136277l.jpg",
   },
   webp: {
    image_url: "https://cdn.myanimelist.net/images/anime/1007/136277.webp",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1007/136277t.webp",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1007/136277l.webp",
   },
  },
  trailer: {
   youtube_id: "MU-Vk5R0vVY",
   url: "https://www.youtube.com/watch?v=MU-Vk5R0vVY",
   embed_url: "https://www.youtube.com/embed/MU-Vk5R0vVY?enablejsapi=1&wmode=opaque&autoplay=1",
   images: {
    image_url: "https://img.youtube.com/vi/MU-Vk5R0vVY/default.jpg",
    small_image_url: "https://img.youtube.com/vi/MU-Vk5R0vVY/sddefault.jpg",
    medium_image_url: "https://img.youtube.com/vi/MU-Vk5R0vVY/mqdefault.jpg",
    large_image_url: "https://img.youtube.com/vi/MU-Vk5R0vVY/hqdefault.jpg",
    maximum_image_url: "https://img.youtube.com/vi/MU-Vk5R0vVY/maxresdefault.jpg",
   },
  },
  approved: true,
  titles: [
   {
    type: "Default",
    title: "Horimiya: Piece",
   },
   {
    type: "Japanese",
    title: "ホリミヤ -piece-",
   },
   {
    type: "English",
    title: "Horimiya: The Missing Pieces",
   },
  ],
  title: "Horimiya: Piece",
  title_english: "Horimiya: The Missing Pieces",
  title_japanese: "ホリミヤ -piece-",
  title_synonyms: [],
  type: "TV",
  source: "Manga",
  episodes: 13,
  status: "Currently Airing",
  airing: true,
  aired: {
   from: "2023-07-01T00:00:00+00:00",
   to: null,
   prop: {
    from: {
     day: 1,
     month: 7,
     year: 2023,
    },
    to: {
     day: null,
     month: null,
     year: null,
    },
   },
   string: "Jul 1, 2023 to ?",
  },
  duration: "23 min per ep",
  rating: "PG-13 - Teens 13 or older",
  score: 8.21,
  scored_by: 29283,
  rank: 336,
  popularity: 1080,
  members: 211306,
  favorites: 1439,
  synopsis:
   "As the graduation ceremony at Katagiri High School comes to an end, Kyouko Hori, her boyfriend Izumi Miyamura, and their friends begin to look back on their time as students. The moments they shared together may be fleeting, but each one is a colorful piece of their precious memories.\n\n[Written by MAL Rewrite]",
  background: "Horimiya: Piece adapts stories from the manga that were not included in the main anime series.",
  season: "summer",
  year: 2023,
  broadcast: {
   day: "Saturdays",
   time: "23:30",
   timezone: "Asia/Tokyo",
   string: "Saturdays at 23:30 (JST)",
  },
  producers: [
   {
    mal_id: 17,
    type: "anime",
    name: "Aniplex",
    url: "https://myanimelist.net/anime/producer/17/Aniplex",
   },
   {
    mal_id: 58,
    type: "anime",
    name: "Square Enix",
    url: "https://myanimelist.net/anime/producer/58/Square_Enix",
   },
   {
    mal_id: 143,
    type: "anime",
    name: "Mainichi Broadcasting System",
    url: "https://myanimelist.net/anime/producer/143/Mainichi_Broadcasting_System",
   },
   {
    mal_id: 166,
    type: "anime",
    name: "Movic",
    url: "https://myanimelist.net/anime/producer/166/Movic",
   },
   {
    mal_id: 1677,
    type: "anime",
    name: "Kanetsu Investment",
    url: "https://myanimelist.net/anime/producer/1677/Kanetsu_Investment",
   },
   {
    mal_id: 2095,
    type: "anime",
    name: "Global Solutions",
    url: "https://myanimelist.net/anime/producer/2095/Global_Solutions",
   },
   {
    mal_id: 2186,
    type: "anime",
    name: "Mirai-Kojo",
    url: "https://myanimelist.net/anime/producer/2186/Mirai-Kojo",
   },
  ],
  licensors: [],
  studios: [
   {
    mal_id: 1835,
    type: "anime",
    name: "CloverWorks",
    url: "https://myanimelist.net/anime/producer/1835/CloverWorks",
   },
  ],
  genres: [
   {
    mal_id: 22,
    type: "anime",
    name: "Romance",
    url: "https://myanimelist.net/anime/genre/22/Romance",
   },
  ],
  explicit_genres: [],
  themes: [
   {
    mal_id: 23,
    type: "anime",
    name: "School",
    url: "https://myanimelist.net/anime/genre/23/School",
   },
  ],
  demographics: [
   {
    mal_id: 27,
    type: "anime",
    name: "Shounen",
    url: "https://myanimelist.net/anime/genre/27/Shounen",
   },
  ],
 },
 {
  mal_id: 47160,
  url: "https://myanimelist.net/anime/47160/Goblin_Slayer_II",
  images: {
   jpg: {
    image_url: "https://cdn.myanimelist.net/images/anime/1569/134760.jpg",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1569/134760t.jpg",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1569/134760l.jpg",
   },
   webp: {
    image_url: "https://cdn.myanimelist.net/images/anime/1569/134760.webp",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1569/134760t.webp",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1569/134760l.webp",
   },
  },
  trailer: {
   youtube_id: "Dc3U12kH3WA",
   url: "https://www.youtube.com/watch?v=Dc3U12kH3WA",
   embed_url: "https://www.youtube.com/embed/Dc3U12kH3WA?enablejsapi=1&wmode=opaque&autoplay=1",
   images: {
    image_url: "https://img.youtube.com/vi/Dc3U12kH3WA/default.jpg",
    small_image_url: "https://img.youtube.com/vi/Dc3U12kH3WA/sddefault.jpg",
    medium_image_url: "https://img.youtube.com/vi/Dc3U12kH3WA/mqdefault.jpg",
    large_image_url: "https://img.youtube.com/vi/Dc3U12kH3WA/hqdefault.jpg",
    maximum_image_url: "https://img.youtube.com/vi/Dc3U12kH3WA/maxresdefault.jpg",
   },
  },
  approved: true,
  titles: [
   {
    type: "Default",
    title: "Goblin Slayer II",
   },
   {
    type: "Synonym",
    title: "Goblin Slayer 2nd Season",
   },
   {
    type: "Japanese",
    title: "ゴブリンスレイヤー II",
   },
  ],
  title: "Goblin Slayer II",
  title_english: null,
  title_japanese: "ゴブリンスレイヤー II",
  title_synonyms: ["Goblin Slayer 2nd Season"],
  type: "TV",
  source: "Light novel",
  episodes: null,
  status: "Currently Airing",
  airing: true,
  aired: {
   from: "2023-08-04T00:00:00+00:00",
   to: null,
   prop: {
    from: {
     day: 4,
     month: 8,
     year: 2023,
    },
    to: {
     day: null,
     month: null,
     year: null,
    },
   },
   string: "Aug 4, 2023 to ?",
  },
  duration: "Unknown",
  rating: "R - 17+ (violence & profanity)",
  score: 7.17,
  scored_by: 343,
  rank: 3360,
  popularity: 1147,
  members: 196725,
  favorites: 2174,
  synopsis:
   "Second season of Goblin Slayer.\n\nEpisodes 1 and 2 were previewed at a screening at AnimagiC in Mannheim, Germany on August 4, 2023. Regular broadcasting began in October 2023.",
  background: null,
  season: "summer",
  year: 2023,
  broadcast: {
   day: null,
   time: null,
   timezone: null,
   string: "Unknown",
  },
  producers: [],
  licensors: [],
  studios: [
   {
    mal_id: 839,
    type: "anime",
    name: "LIDENFILMS",
    url: "https://myanimelist.net/anime/producer/839/LIDENFILMS",
   },
  ],
  genres: [
   {
    mal_id: 1,
    type: "anime",
    name: "Action",
    url: "https://myanimelist.net/anime/genre/1/Action",
   },
   {
    mal_id: 2,
    type: "anime",
    name: "Adventure",
    url: "https://myanimelist.net/anime/genre/2/Adventure",
   },
   {
    mal_id: 10,
    type: "anime",
    name: "Fantasy",
    url: "https://myanimelist.net/anime/genre/10/Fantasy",
   },
  ],
  explicit_genres: [],
  themes: [],
  demographics: [],
 },
 {
  mal_id: 53998,
  url: "https://myanimelist.net/anime/53998/Bleach__Sennen_Kessen-hen_-_Ketsubetsu-tan",
  images: {
   jpg: {
    image_url: "https://cdn.myanimelist.net/images/anime/1018/136667.jpg",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1018/136667t.jpg",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1018/136667l.jpg",
   },
   webp: {
    image_url: "https://cdn.myanimelist.net/images/anime/1018/136667.webp",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1018/136667t.webp",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1018/136667l.webp",
   },
  },
  trailer: {
   youtube_id: "m_i2PinZ_X4",
   url: "https://www.youtube.com/watch?v=m_i2PinZ_X4",
   embed_url: "https://www.youtube.com/embed/m_i2PinZ_X4?enablejsapi=1&wmode=opaque&autoplay=1",
   images: {
    image_url: "https://img.youtube.com/vi/m_i2PinZ_X4/default.jpg",
    small_image_url: "https://img.youtube.com/vi/m_i2PinZ_X4/sddefault.jpg",
    medium_image_url: "https://img.youtube.com/vi/m_i2PinZ_X4/mqdefault.jpg",
    large_image_url: "https://img.youtube.com/vi/m_i2PinZ_X4/hqdefault.jpg",
    maximum_image_url: "https://img.youtube.com/vi/m_i2PinZ_X4/maxresdefault.jpg",
   },
  },
  approved: true,
  titles: [
   {
    type: "Default",
    title: "Bleach: Sennen Kessen-hen - Ketsubetsu-tan",
   },
   {
    type: "Synonym",
    title: "Bleach: Thousand-Year Blood War Arc",
   },
   {
    type: "Japanese",
    title: "BLEACH 千年血戦篇-訣別譚-",
   },
   {
    type: "English",
    title: "Bleach: Thousand-Year Blood War - The Separation",
   },
  ],
  title: "Bleach: Sennen Kessen-hen - Ketsubetsu-tan",
  title_english: "Bleach: Thousand-Year Blood War - The Separation",
  title_japanese: "BLEACH 千年血戦篇-訣別譚-",
  title_synonyms: ["Bleach: Thousand-Year Blood War Arc"],
  type: "TV",
  source: "Manga",
  episodes: 13,
  status: "Currently Airing",
  airing: true,
  aired: {
   from: "2023-07-08T00:00:00+00:00",
   to: null,
   prop: {
    from: {
     day: 8,
     month: 7,
     year: 2023,
    },
    to: {
     day: null,
     month: null,
     year: null,
    },
   },
   string: "Jul 8, 2023 to ?",
  },
  duration: "24 min per ep",
  rating: "R - 17+ (violence & profanity)",
  score: 8.97,
  scored_by: 30522,
  rank: 15,
  popularity: 1313,
  members: 170608,
  favorites: 2418,
  synopsis: "Second cour of Bleach: Sennen Kessen-hen.",
  background:
   "The anime adapts the final manga arc, Sennen Kessen-hen (Thousand-Year Blood War Arc), which spans from the 55th to the 74th volumes.",
  season: "summer",
  year: 2023,
  broadcast: {
   day: "Saturdays",
   time: "23:00",
   timezone: "Asia/Tokyo",
   string: "Saturdays at 23:00 (JST)",
  },
  producers: [
   {
    mal_id: 16,
    type: "anime",
    name: "TV Tokyo",
    url: "https://myanimelist.net/anime/producer/16/TV_Tokyo",
   },
   {
    mal_id: 17,
    type: "anime",
    name: "Aniplex",
    url: "https://myanimelist.net/anime/producer/17/Aniplex",
   },
   {
    mal_id: 53,
    type: "anime",
    name: "Dentsu",
    url: "https://myanimelist.net/anime/producer/53/Dentsu",
   },
   {
    mal_id: 1365,
    type: "anime",
    name: "Shueisha",
    url: "https://myanimelist.net/anime/producer/1365/Shueisha",
   },
   {
    mal_id: 1392,
    type: "anime",
    name: "Zack Promotion",
    url: "https://myanimelist.net/anime/producer/1392/Zack_Promotion",
   },
  ],
  licensors: [],
  studios: [
   {
    mal_id: 1,
    type: "anime",
    name: "Pierrot",
    url: "https://myanimelist.net/anime/producer/1/Pierrot",
   },
  ],
  genres: [
   {
    mal_id: 1,
    type: "anime",
    name: "Action",
    url: "https://myanimelist.net/anime/genre/1/Action",
   },
   {
    mal_id: 2,
    type: "anime",
    name: "Adventure",
    url: "https://myanimelist.net/anime/genre/2/Adventure",
   },
   {
    mal_id: 10,
    type: "anime",
    name: "Fantasy",
    url: "https://myanimelist.net/anime/genre/10/Fantasy",
   },
  ],
  explicit_genres: [],
  themes: [],
  demographics: [
   {
    mal_id: 27,
    type: "anime",
    name: "Shounen",
    url: "https://myanimelist.net/anime/genre/27/Shounen",
   },
  ],
 },
 {
  mal_id: 51552,
  url: "https://myanimelist.net/anime/51552/Watashi_no_Shiawase_na_Kekkon",
  images: {
   jpg: {
    image_url: "https://cdn.myanimelist.net/images/anime/1147/122444.jpg",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1147/122444t.jpg",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1147/122444l.jpg",
   },
   webp: {
    image_url: "https://cdn.myanimelist.net/images/anime/1147/122444.webp",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1147/122444t.webp",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1147/122444l.webp",
   },
  },
  trailer: {
   youtube_id: "dURh9kVzcw8",
   url: "https://www.youtube.com/watch?v=dURh9kVzcw8",
   embed_url: "https://www.youtube.com/embed/dURh9kVzcw8?enablejsapi=1&wmode=opaque&autoplay=1",
   images: {
    image_url: "https://img.youtube.com/vi/dURh9kVzcw8/default.jpg",
    small_image_url: "https://img.youtube.com/vi/dURh9kVzcw8/sddefault.jpg",
    medium_image_url: "https://img.youtube.com/vi/dURh9kVzcw8/mqdefault.jpg",
    large_image_url: "https://img.youtube.com/vi/dURh9kVzcw8/hqdefault.jpg",
    maximum_image_url: "https://img.youtube.com/vi/dURh9kVzcw8/maxresdefault.jpg",
   },
  },
  approved: true,
  titles: [
   {
    type: "Default",
    title: "Watashi no Shiawase na Kekkon",
   },
   {
    type: "Synonym",
    title: "My Blissful Marriage",
   },
   {
    type: "Japanese",
    title: "わたしの幸せな結婚",
   },
   {
    type: "English",
    title: "My Happy Marriage",
   },
  ],
  title: "Watashi no Shiawase na Kekkon",
  title_english: "My Happy Marriage",
  title_japanese: "わたしの幸せな結婚",
  title_synonyms: ["My Blissful Marriage"],
  type: "TV",
  source: "Novel",
  episodes: 12,
  status: "Currently Airing",
  airing: true,
  aired: {
   from: "2023-07-05T00:00:00+00:00",
   to: null,
   prop: {
    from: {
     day: 5,
     month: 7,
     year: 2023,
    },
    to: {
     day: null,
     month: null,
     year: null,
    },
   },
   string: "Jul 5, 2023 to ?",
  },
  duration: "23 min per ep",
  rating: "PG-13 - Teens 13 or older",
  score: 8.36,
  scored_by: 27029,
  rank: 200,
  popularity: 1411,
  members: 156607,
  favorites: 1356,
  synopsis:
   "Miyo Saimori was the unfortunate child of a loveless, arranged marriage. After her mother died, her father brought in his lover and her own daughter, Kaya. From then on, Miyo's life was reduced to that of a mere servant. Even worse, while Kaya inherited the family's psychic abilities, Miyo had none—she was truly the daughter with no merit.\n\nAfter years of being treated like dirt, Miyo has learned to keep her head down, hide her pain, and obey every order. So, it comes as no surprise that she is arranged to be married to Kiyoka Kudou, a military captain rumored to be so cruel that he has driven away every one of his potential wives so far.\n\nFrom a painful upbringing to a painful marriage, that's the future that awaits Miyo—or so she thinks. Contrary to her expectations, her new husband is actually kind-hearted. What really awaits Miyo is a blissful, everlasting marriage full of happiness! \n\n[Written by MAL Rewrite]",
  background: null,
  season: "summer",
  year: 2023,
  broadcast: {
   day: "Wednesdays",
   time: "23:30",
   timezone: "Asia/Tokyo",
   string: "Wednesdays at 23:30 (JST)",
  },
  producers: [
   {
    mal_id: 58,
    type: "anime",
    name: "Square Enix",
    url: "https://myanimelist.net/anime/producer/58/Square_Enix",
   },
   {
    mal_id: 1255,
    type: "anime",
    name: "Glovision",
    url: "https://myanimelist.net/anime/producer/1255/Glovision",
   },
   {
    mal_id: 1390,
    type: "anime",
    name: "Toy's Factory",
    url: "https://myanimelist.net/anime/producer/1390/Toys_Factory",
   },
   {
    mal_id: 1406,
    type: "anime",
    name: "Miracle Bus",
    url: "https://myanimelist.net/anime/producer/1406/Miracle_Bus",
   },
   {
    mal_id: 1696,
    type: "anime",
    name: "Kadokawa",
    url: "https://myanimelist.net/anime/producer/1696/Kadokawa",
   },
   {
    mal_id: 2425,
    type: "anime",
    name: "Bandai Namco Music Live",
    url: "https://myanimelist.net/anime/producer/2425/Bandai_Namco_Music_Live",
   },
  ],
  licensors: [],
  studios: [
   {
    mal_id: 290,
    type: "anime",
    name: "Kinema Citrus",
    url: "https://myanimelist.net/anime/producer/290/Kinema_Citrus",
   },
  ],
  genres: [
   {
    mal_id: 10,
    type: "anime",
    name: "Fantasy",
    url: "https://myanimelist.net/anime/genre/10/Fantasy",
   },
   {
    mal_id: 22,
    type: "anime",
    name: "Romance",
    url: "https://myanimelist.net/anime/genre/22/Romance",
   },
  ],
  explicit_genres: [],
  themes: [
   {
    mal_id: 13,
    type: "anime",
    name: "Historical",
    url: "https://myanimelist.net/anime/genre/13/Historical",
   },
  ],
  demographics: [],
 },
 {
  mal_id: 51498,
  url: "https://myanimelist.net/anime/51498/Masamune-kun_no_Revenge_R",
  images: {
   jpg: {
    image_url: "https://cdn.myanimelist.net/images/anime/1667/135587.jpg",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1667/135587t.jpg",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1667/135587l.jpg",
   },
   webp: {
    image_url: "https://cdn.myanimelist.net/images/anime/1667/135587.webp",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1667/135587t.webp",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1667/135587l.webp",
   },
  },
  trailer: {
   youtube_id: "i7x4De9e8qY",
   url: "https://www.youtube.com/watch?v=i7x4De9e8qY",
   embed_url: "https://www.youtube.com/embed/i7x4De9e8qY?enablejsapi=1&wmode=opaque&autoplay=1",
   images: {
    image_url: "https://img.youtube.com/vi/i7x4De9e8qY/default.jpg",
    small_image_url: "https://img.youtube.com/vi/i7x4De9e8qY/sddefault.jpg",
    medium_image_url: "https://img.youtube.com/vi/i7x4De9e8qY/mqdefault.jpg",
    large_image_url: "https://img.youtube.com/vi/i7x4De9e8qY/hqdefault.jpg",
    maximum_image_url: "https://img.youtube.com/vi/i7x4De9e8qY/maxresdefault.jpg",
   },
  },
  approved: true,
  titles: [
   {
    type: "Default",
    title: "Masamune-kun no Revenge R",
   },
   {
    type: "Japanese",
    title: "政宗くんのリベンジR",
   },
   {
    type: "English",
    title: "Masamune-kun's Revenge R",
   },
  ],
  title: "Masamune-kun no Revenge R",
  title_english: "Masamune-kun's Revenge R",
  title_japanese: "政宗くんのリベンジR",
  title_synonyms: [],
  type: "TV",
  source: "Manga",
  episodes: 12,
  status: "Currently Airing",
  airing: true,
  aired: {
   from: "2023-07-03T00:00:00+00:00",
   to: null,
   prop: {
    from: {
     day: 3,
     month: 7,
     year: 2023,
    },
    to: {
     day: null,
     month: null,
     year: null,
    },
   },
   string: "Jul 3, 2023 to ?",
  },
  duration: "23 min per ep",
  rating: "PG-13 - Teens 13 or older",
  score: 7.26,
  scored_by: 14414,
  rank: 2831,
  popularity: 1473,
  members: 147376,
  favorites: 987,
  synopsis:
   "It's time for a class trip to Paris! When they get there, Aki and Masamune soon cross paths with a French otaku. They agree to help her with the manga she's making, but soon realize they're in way over their heads. Modeling, threats from the mafia, and a fake date—their school trip is proving to be far more exciting than they ever could have imagined!\n\n(Source: Seven Seas)",
  background: null,
  season: "summer",
  year: 2023,
  broadcast: {
   day: "Mondays",
   time: "21:00",
   timezone: "Asia/Tokyo",
   string: "Mondays at 21:00 (JST)",
  },
  producers: [
   {
    mal_id: 104,
    type: "anime",
    name: "Lantis",
    url: "https://myanimelist.net/anime/producer/104/Lantis",
   },
   {
    mal_id: 238,
    type: "anime",
    name: "AT-X",
    url: "https://myanimelist.net/anime/producer/238/AT-X",
   },
   {
    mal_id: 460,
    type: "anime",
    name: "KlockWorx",
    url: "https://myanimelist.net/anime/producer/460/KlockWorx",
   },
   {
    mal_id: 843,
    type: "anime",
    name: "BS Fuji",
    url: "https://myanimelist.net/anime/producer/843/BS_Fuji",
   },
   {
    mal_id: 1211,
    type: "anime",
    name: "Tokyo MX",
    url: "https://myanimelist.net/anime/producer/1211/Tokyo_MX",
   },
   {
    mal_id: 1468,
    type: "anime",
    name: "Crunchyroll",
    url: "https://myanimelist.net/anime/producer/1468/Crunchyroll",
   },
   {
    mal_id: 1582,
    type: "anime",
    name: "Ichijinsha",
    url: "https://myanimelist.net/anime/producer/1582/Ichijinsha",
   },
   {
    mal_id: 1590,
    type: "anime",
    name: "FuRyu",
    url: "https://myanimelist.net/anime/producer/1590/FuRyu",
   },
   {
    mal_id: 2031,
    type: "anime",
    name: "Lawson Entertainment",
    url: "https://myanimelist.net/anime/producer/2031/Lawson_Entertainment",
   },
   {
    mal_id: 2425,
    type: "anime",
    name: "Bandai Namco Music Live",
    url: "https://myanimelist.net/anime/producer/2425/Bandai_Namco_Music_Live",
   },
  ],
  licensors: [],
  studios: [
   {
    mal_id: 300,
    type: "anime",
    name: "SILVER LINK.",
    url: "https://myanimelist.net/anime/producer/300/SILVER_LINK",
   },
  ],
  genres: [
   {
    mal_id: 4,
    type: "anime",
    name: "Comedy",
    url: "https://myanimelist.net/anime/genre/4/Comedy",
   },
   {
    mal_id: 22,
    type: "anime",
    name: "Romance",
    url: "https://myanimelist.net/anime/genre/22/Romance",
   },
  ],
  explicit_genres: [],
  themes: [
   {
    mal_id: 35,
    type: "anime",
    name: "Harem",
    url: "https://myanimelist.net/anime/genre/35/Harem",
   },
   {
    mal_id: 23,
    type: "anime",
    name: "School",
    url: "https://myanimelist.net/anime/genre/23/School",
   },
  ],
  demographics: [
   {
    mal_id: 27,
    type: "anime",
    name: "Shounen",
    url: "https://myanimelist.net/anime/genre/27/Shounen",
   },
  ],
 },
 {
  mal_id: 54234,
  url: "https://myanimelist.net/anime/54234/Suki_na_Ko_ga_Megane_wo_Wasureta",
  images: {
   jpg: {
    image_url: "https://cdn.myanimelist.net/images/anime/1582/136325.jpg",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1582/136325t.jpg",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1582/136325l.jpg",
   },
   webp: {
    image_url: "https://cdn.myanimelist.net/images/anime/1582/136325.webp",
    small_image_url: "https://cdn.myanimelist.net/images/anime/1582/136325t.webp",
    large_image_url: "https://cdn.myanimelist.net/images/anime/1582/136325l.webp",
   },
  },
  trailer: {
   youtube_id: "45lyCUdzRx4",
   url: "https://www.youtube.com/watch?v=45lyCUdzRx4",
   embed_url: "https://www.youtube.com/embed/45lyCUdzRx4?enablejsapi=1&wmode=opaque&autoplay=1",
   images: {
    image_url: "https://img.youtube.com/vi/45lyCUdzRx4/default.jpg",
    small_image_url: "https://img.youtube.com/vi/45lyCUdzRx4/sddefault.jpg",
    medium_image_url: "https://img.youtube.com/vi/45lyCUdzRx4/mqdefault.jpg",
    large_image_url: "https://img.youtube.com/vi/45lyCUdzRx4/hqdefault.jpg",
    maximum_image_url: "https://img.youtube.com/vi/45lyCUdzRx4/maxresdefault.jpg",
   },
  },
  approved: true,
  titles: [
   {
    type: "Default",
    title: "Suki na Ko ga Megane wo Wasureta",
   },
   {
    type: "Japanese",
    title: "好きな子がめがねを忘れた",
   },
   {
    type: "English",
    title: "The Girl I Like Forgot Her Glasses",
   },
  ],
  title: "Suki na Ko ga Megane wo Wasureta",
  title_english: "The Girl I Like Forgot Her Glasses",
  title_japanese: "好きな子がめがねを忘れた",
  title_synonyms: [],
  type: "TV",
  source: "Manga",
  episodes: 13,
  status: "Currently Airing",
  airing: true,
  aired: {
   from: "2023-07-04T00:00:00+00:00",
   to: null,
   prop: {
    from: {
     day: 4,
     month: 7,
     year: 2023,
    },
    to: {
     day: null,
     month: null,
     year: null,
    },
   },
   string: "Jul 4, 2023 to ?",
  },
  duration: "23 min per ep",
  rating: "PG-13 - Teens 13 or older",
  score: 6.91,
  scored_by: 20448,
  rank: 4452,
  popularity: 1558,
  members: 137024,
  favorites: 943,
  synopsis:
   "As the deskmate of Ai Mie, Kaede Komura always has his attention fixed on her. Attracted by her cute charms, all he wishes for is that she would look at him with those beautiful eyes beneath her glasses. But just a few days after making her acquaintance, Kaede notices something different about Ai: her eyes are squinting and her glasses are missing. Nonetheless, he still finds her adorable!\n\nUnexpectedly, Ai has a tendency to forget her glasses. Having terrible vision, she has difficulty going through her day at school. Thankfully, Kaede is more than willing to help her. As Ai starts relying on him, Kaede's feelings for her grow even more. Likewise, despite her short-sightedness, Kaede slowly becomes the person Ai always hopes to see.\n\n[Written by MAL Rewrite]",
  background: null,
  season: "summer",
  year: 2023,
  broadcast: {
   day: "Tuesdays",
   time: "23:00",
   timezone: "Asia/Tokyo",
   string: "Tuesdays at 23:00 (JST)",
  },
  producers: [
   {
    mal_id: 58,
    type: "anime",
    name: "Square Enix",
    url: "https://myanimelist.net/anime/producer/58/Square_Enix",
   },
   {
    mal_id: 109,
    type: "anime",
    name: "Shochiku",
    url: "https://myanimelist.net/anime/producer/109/Shochiku",
   },
   {
    mal_id: 464,
    type: "anime",
    name: "flying DOG",
    url: "https://myanimelist.net/anime/producer/464/flying_DOG",
   },
   {
    mal_id: 1211,
    type: "anime",
    name: "Tokyo MX",
    url: "https://myanimelist.net/anime/producer/1211/Tokyo_MX",
   },
   {
    mal_id: 1255,
    type: "anime",
    name: "Glovision",
    url: "https://myanimelist.net/anime/producer/1255/Glovision",
   },
   {
    mal_id: 1333,
    type: "anime",
    name: "Hakuhodo DY Music & Pictures",
    url: "https://myanimelist.net/anime/producer/1333/Hakuhodo_DY_Music___Pictures",
   },
   {
    mal_id: 1583,
    type: "anime",
    name: "U-NEXT",
    url: "https://myanimelist.net/anime/producer/1583/U-NEXT",
   },
   {
    mal_id: 1590,
    type: "anime",
    name: "FuRyu",
    url: "https://myanimelist.net/anime/producer/1590/FuRyu",
   },
   {
    mal_id: 2185,
    type: "anime",
    name: "BS Asahi",
    url: "https://myanimelist.net/anime/producer/2185/BS_Asahi",
   },
  ],
  licensors: [],
  studios: [
   {
    mal_id: 309,
    type: "anime",
    name: "GoHands",
    url: "https://myanimelist.net/anime/producer/309/GoHands",
   },
  ],
  genres: [
   {
    mal_id: 4,
    type: "anime",
    name: "Comedy",
    url: "https://myanimelist.net/anime/genre/4/Comedy",
   },
  ],
  explicit_genres: [],
  themes: [
   {
    mal_id: 74,
    type: "anime",
    name: "Romantic Subtext",
    url: "https://myanimelist.net/anime/genre/74/Romantic_Subtext",
   },
   {
    mal_id: 23,
    type: "anime",
    name: "School",
    url: "https://myanimelist.net/anime/genre/23/School",
   },
  ],
  demographics: [
   {
    mal_id: 27,
    type: "anime",
    name: "Shounen",
    url: "https://myanimelist.net/anime/genre/27/Shounen",
   },
  ],
 },
];

export default DataAnimeWorldExample;
